export const demoDeposits = [
  {
    id: 'fd-1',
    srNo: 1,
    bankName: 'State Bank of India',
    branchCity: 'Jaipur',
    holderName: 'Me',
    fundingSource: 'Me',
    instrumentType: 'Bank FD',
    payoutMode: 'on-maturity',
    yearlyPayoutMonthDay: '',
    interestPayoutBeforeTds: '',
    interestPayoutAfterTds: '',
    accountNumber: 'SBI-FD-1048',
    tenure: '1 Year',
    interestRate: 7.1,
    principalAmount: 100000,
    investmentDate: '2025-04-15',
    maturityDate: '2026-04-15',
    maturityBeforeTax: 107100,
    maturityAfterTax: '',
    totalInterestEarned: '',
    tdsPercent: 10,
    tdsAmount: '',
    status: 'Open',
    allocations: [],
    notes: 'Renewal candidate for April cash flow.',
  },
  {
    id: 'fd-2',
    srNo: 2,
    bankName: 'HDFC Bank',
    branchCity: 'Jaipur',
    holderName: 'Wife',
    fundingSource: 'Me',
    instrumentType: 'Bank FD',
    payoutMode: 'on-maturity',
    yearlyPayoutMonthDay: '',
    interestPayoutBeforeTds: '',
    interestPayoutAfterTds: '',
    accountNumber: 'HDFC-FD-2881',
    tenure: '444 Days',
    interestRate: 7.45,
    principalAmount: 150000,
    investmentDate: '2024-02-26',
    maturityDate: '2025-05-15',
    maturityBeforeTax: 164400,
    maturityAfterTax: 163000,
    totalInterestEarned: 13000,
    tdsPercent: 10,
    tdsAmount: 1400,
    status: 'Closed',
    allocations: [],
    notes: 'Matured and fully allocated into three follow-up deposits.',
  },
  {
    id: 'fd-3',
    srNo: 3,
    bankName: 'ICICI Bank',
    branchCity: 'Jaipur',
    holderName: 'Kid',
    fundingSource: 'Wife',
    instrumentType: 'Bank FD',
    payoutMode: 'on-maturity',
    yearlyPayoutMonthDay: '',
    interestPayoutBeforeTds: '',
    interestPayoutAfterTds: '',
    accountNumber: 'ICICI-FD-8127',
    tenure: '18 Months',
    interestRate: 7.3,
    principalAmount: 90000,
    investmentDate: '2025-05-16',
    maturityDate: '2026-11-16',
    maturityBeforeTax: 100700,
    maturityAfterTax: '',
    totalInterestEarned: '',
    tdsPercent: 10,
    tdsAmount: '',
    status: 'Open',
    allocations: [{ eventId: 'maturity:fd-2', amount: 90000 }],
    notes: 'One branch of the maturity reinvestment chain.',
  },
  {
    id: 'fd-4',
    srNo: 4,
    bankName: 'Axis Bank',
    branchCity: 'Jaipur',
    holderName: 'Me',
    fundingSource: 'Wife',
    instrumentType: 'Bank FD',
    payoutMode: 'on-maturity',
    yearlyPayoutMonthDay: '',
    interestPayoutBeforeTds: '',
    interestPayoutAfterTds: '',
    accountNumber: 'AXIS-FD-3980',
    tenure: '1 Year',
    interestRate: 7.05,
    principalAmount: 70000,
    investmentDate: '2025-05-16',
    maturityDate: '2026-05-16',
    maturityBeforeTax: 74935,
    maturityAfterTax: '',
    totalInterestEarned: '',
    tdsPercent: 10,
    tdsAmount: '',
    status: 'Open',
    allocations: [{ eventId: 'maturity:fd-2', amount: 70000 }],
    notes: 'Second part of the same maturity reinvested.',
  },
  {
    id: 'fd-5',
    srNo: 5,
    bankName: 'Post Office',
    branchCity: 'Jaipur',
    holderName: 'Mother',
    fundingSource: 'Me',
    instrumentType: 'SCSS',
    payoutMode: 'quarterly-fy',
    yearlyPayoutMonthDay: '',
    interestPayoutBeforeTds: 6150,
    interestPayoutAfterTds: 5535,
    accountNumber: 'SCSS-2025-7712',
    tenure: '5 Year',
    interestRate: 8.2,
    principalAmount: 300000,
    investmentDate: '2025-04-10',
    maturityDate: '2030-04-10',
    maturityBeforeTax: 300000,
    maturityAfterTax: '',
    totalInterestEarned: '',
    tdsPercent: 10,
    tdsAmount: '',
    status: 'Open',
    allocations: [],
    notes: 'Quarterly interest credited at financial year quarter end.',
  },
  {
    id: 'fd-6',
    srNo: 6,
    bankName: 'REC Bond',
    branchCity: 'Jaipur',
    holderName: 'Me',
    fundingSource: 'Me',
    instrumentType: 'Bond',
    payoutMode: 'yearly-fixed',
    yearlyPayoutMonthDay: '07-15',
    interestPayoutBeforeTds: 15500,
    interestPayoutAfterTds: 13950,
    accountNumber: 'REC-2025-9911',
    tenure: '5 Year',
    interestRate: 7.75,
    principalAmount: 200000,
    investmentDate: '2024-07-15',
    maturityDate: '2029-07-15',
    maturityBeforeTax: 200000,
    maturityAfterTax: '',
    totalInterestEarned: '',
    tdsPercent: 10,
    tdsAmount: '',
    status: 'Open',
    allocations: [],
    notes: 'Annual coupon style payout on fixed date.',
  },
  {
    id: 'fd-7',
    srNo: 7,
    bankName: 'Union Bank of India',
    branchCity: 'Jaipur',
    holderName: 'Mother',
    fundingSource: 'Mother',
    instrumentType: 'Bank FD',
    payoutMode: 'on-maturity',
    yearlyPayoutMonthDay: '',
    interestPayoutBeforeTds: '',
    interestPayoutAfterTds: '',
    accountNumber: 'UBI-FD-5510',
    tenure: '1 Year',
    interestRate: 6.9,
    principalAmount: 4500,
    investmentDate: '2025-07-02',
    maturityDate: '2026-07-02',
    maturityBeforeTax: 4811,
    maturityAfterTax: '',
    totalInterestEarned: '',
    tdsPercent: 10,
    tdsAmount: '',
    status: 'Open',
    allocations: [{ eventId: 'interest:fd-5:2025-06-30', amount: 4500 }],
    notes: 'Funded using the first SCSS quarterly interest credit.',
  },
  {
    id: 'fd-8',
    srNo: 8,
    bankName: 'IDFC First Bank',
    branchCity: 'Jaipur',
    holderName: 'Me',
    fundingSource: 'Me',
    instrumentType: 'Bank FD',
    payoutMode: 'on-maturity',
    yearlyPayoutMonthDay: '',
    interestPayoutBeforeTds: '',
    interestPayoutAfterTds: '',
    accountNumber: 'IDFC-FD-2218',
    tenure: '1 Year',
    interestRate: 7.25,
    principalAmount: 15000,
    investmentDate: '2025-10-05',
    maturityDate: '2026-10-05',
    maturityBeforeTax: 16088,
    maturityAfterTax: '',
    totalInterestEarned: '',
    tdsPercent: 10,
    tdsAmount: '',
    status: 'Open',
    allocations: [
      { eventId: 'interest:fd-5:2025-09-30', amount: 5000 },
      { eventId: 'interest:fd-6:2025-07-15', amount: 10000 },
    ],
    notes: 'Mixed-source reinvestment from SCSS and REC interest.',
  },
  {
    id: 'fd-9',
    srNo: 9,
    bankName: 'Canara Bank',
    branchCity: 'Jaipur',
    holderName: 'Me',
    fundingSource: 'Me',
    instrumentType: 'Bank FD',
    payoutMode: 'on-maturity',
    yearlyPayoutMonthDay: '',
    interestPayoutBeforeTds: '',
    interestPayoutAfterTds: '',
    accountNumber: 'CAN-FD-3201',
    tenure: '400 Days',
    interestRate: 7.1,
    principalAmount: 50000,
    investmentDate: '2024-01-15',
    maturityDate: '2025-02-18',
    maturityBeforeTax: 54200,
    maturityAfterTax: 53800,
    totalInterestEarned: 3800,
    tdsPercent: 10,
    tdsAmount: 400,
    status: 'Closed',
    allocations: [],
    notes: 'Closed deposit kept fully uninvested for upcoming expenses.',
  },
  {
    id: 'fd-10',
    srNo: 10,
    bankName: 'Kotak Mahindra Bank',
    branchCity: 'Jaipur',
    holderName: 'Me',
    fundingSource: 'Mixed',
    instrumentType: 'Bank FD',
    payoutMode: 'on-maturity',
    yearlyPayoutMonthDay: '',
    interestPayoutBeforeTds: '',
    interestPayoutAfterTds: '',
    accountNumber: 'KOTAK-FD-8804',
    tenure: '9 Months',
    interestRate: 7.15,
    principalAmount: 10000,
    investmentDate: '2026-01-10',
    maturityDate: '2026-10-10',
    maturityBeforeTax: 10538,
    maturityAfterTax: '',
    totalInterestEarned: '',
    tdsPercent: 10,
    tdsAmount: '',
    status: 'Open',
    allocations: [
      { eventId: 'maturity:fd-2', amount: 3000 },
      { eventId: 'interest:fd-5:2025-12-31', amount: 4000 },
      { eventId: 'interest:fd-6:2025-07-15', amount: 3000 },
    ],
    notes: 'Mixed funding from one maturity pool plus two interest credits.',
  },
  {
    id: 'fd-11',
    srNo: 11,
    bankName: 'Post Office',
    branchCity: 'Jaipur',
    holderName: 'Father',
    fundingSource: 'Father',
    instrumentType: 'SCSS',
    payoutMode: 'quarterly-fy',
    yearlyPayoutMonthDay: '',
    interestPayoutBeforeTds: 9225,
    interestPayoutAfterTds: 8303,
    accountNumber: 'SCSS-2024-1102',
    tenure: '5 Year',
    interestRate: 8.2,
    principalAmount: 450000,
    investmentDate: '2024-04-12',
    maturityDate: '2029-04-12',
    maturityBeforeTax: 450000,
    maturityAfterTax: '',
    totalInterestEarned: '',
    tdsPercent: 10,
    tdsAmount: '',
    status: 'Open',
    allocations: [],
    notes: 'SCSS example where quarterly interest is being left idle for now.',
  },
  {
    id: 'fd-12',
    srNo: 12,
    bankName: 'Punjab National Bank',
    branchCity: 'Jaipur',
    holderName: 'Father',
    fundingSource: 'Father',
    instrumentType: 'Bank FD',
    payoutMode: 'on-maturity',
    yearlyPayoutMonthDay: '',
    interestPayoutBeforeTds: '',
    interestPayoutAfterTds: '',
    accountNumber: 'PNB-FD-7720',
    tenure: '370 Days',
    interestRate: 7.05,
    principalAmount: 8000,
    investmentDate: '2024-10-03',
    maturityDate: '2025-10-08',
    maturityBeforeTax: 8567,
    maturityAfterTax: '',
    totalInterestEarned: '',
    tdsPercent: 10,
    tdsAmount: '',
    status: 'Open',
    allocations: [{ eventId: 'interest:fd-11:2024-09-30', amount: 8000 }],
    notes: 'Quarterly SCSS interest reinvested into a new FD.',
  },
  {
    id: 'fd-13',
    srNo: 13,
    bankName: 'IRFC Bond',
    branchCity: 'Jaipur',
    holderName: 'Wife',
    fundingSource: 'Wife',
    instrumentType: 'Bond',
    payoutMode: 'yearly-fixed',
    yearlyPayoutMonthDay: '12-01',
    interestPayoutBeforeTds: 18500,
    interestPayoutAfterTds: 16650,
    accountNumber: 'IRFC-2023-6621',
    tenure: '5 Year',
    interestRate: 7.4,
    principalAmount: 250000,
    investmentDate: '2023-12-01',
    maturityDate: '2028-12-01',
    maturityBeforeTax: 250000,
    maturityAfterTax: '',
    totalInterestEarned: '',
    tdsPercent: 10,
    tdsAmount: '',
    status: 'Open',
    allocations: [],
    notes: 'Annual bond payout example with no reinvestment yet.',
  },
  {
    id: 'fd-14',
    srNo: 14,
    bankName: 'AU Small Finance Bank',
    branchCity: 'Jaipur',
    holderName: 'Wife',
    fundingSource: 'Wife',
    instrumentType: 'Bank FD',
    payoutMode: 'on-maturity',
    yearlyPayoutMonthDay: '',
    interestPayoutBeforeTds: '',
    interestPayoutAfterTds: '',
    accountNumber: 'AU-FD-4409',
    tenure: '15 Months',
    interestRate: 7.4,
    principalAmount: 12000,
    investmentDate: '2024-12-10',
    maturityDate: '2026-03-10',
    maturityBeforeTax: 13110,
    maturityAfterTax: '',
    totalInterestEarned: '',
    tdsPercent: 10,
    tdsAmount: '',
    status: 'Open',
    allocations: [{ eventId: 'interest:fd-13:2024-12-01', amount: 12000 }],
    notes: 'Annual IRFC bond interest reinvested into a bank FD.',
  },
  {
    id: 'fd-15',
    srNo: 15,
    bankName: 'Bank of Baroda',
    branchCity: 'Jaipur',
    holderName: 'Kid',
    fundingSource: 'Mixed',
    instrumentType: 'Bank FD',
    payoutMode: 'on-maturity',
    yearlyPayoutMonthDay: '',
    interestPayoutBeforeTds: '',
    interestPayoutAfterTds: '',
    accountNumber: 'BOB-FD-6615',
    tenure: '2 Year',
    interestRate: 7,
    principalAmount: 18000,
    investmentDate: '2026-01-05',
    maturityDate: '2028-01-05',
    maturityBeforeTax: 20604,
    maturityAfterTax: '',
    totalInterestEarned: '',
    tdsPercent: 10,
    tdsAmount: '',
    status: 'Open',
    allocations: [
      { eventId: 'interest:fd-11:2024-12-31', amount: 9000 },
      { eventId: 'interest:fd-13:2025-12-01', amount: 9000 },
    ],
    notes: 'One new deposit funded by two different interest events.',
  },
  {
    id: 'fd-16',
    srNo: 16,
    bankName: 'Indian Bank',
    branchCity: 'Jaipur',
    holderName: 'Me',
    fundingSource: 'Me',
    instrumentType: 'Bank FD',
    payoutMode: 'on-maturity',
    yearlyPayoutMonthDay: '',
    interestPayoutBeforeTds: '',
    interestPayoutAfterTds: '',
    accountNumber: 'IND-FD-5100',
    tenure: '2 Year',
    interestRate: 7.15,
    principalAmount: 53800,
    investmentDate: '2025-02-20',
    maturityDate: '2027-02-20',
    maturityBeforeTax: 61887,
    maturityAfterTax: '',
    totalInterestEarned: '',
    tdsPercent: 10,
    tdsAmount: '',
    status: 'Open',
    allocations: [{ eventId: 'maturity:fd-9', amount: 53800 }],
    notes: 'Example where a fully matured deposit is fully rolled over into one new FD.',
  },
]
