export const DEMO_PORTFOLIO_LABEL = 'YieldFlow Demo Portfolio'
export const DEFAULT_DEMO_OWNER_ID = 'demo-owner-yieldflow'

export const demoMasterData = {
  owners: [
    {
      id: 'aarav-mehta',
      name: 'Aarav Mehta',
      ownerType: 'Individual',
      taxSlabRate: 30,
      aliases: ['A Mehta', 'Aarav'],
    },
    {
      id: 'nisha-mehta',
      name: 'Nisha Mehta',
      ownerType: 'Spouse',
      taxSlabRate: 20,
      aliases: ['N Mehta', 'Nisha'],
    },
    {
      id: 'prakash-mehta',
      name: 'Prakash Mehta',
      ownerType: 'Parent',
      taxSlabRate: 10,
      aliases: ['P Mehta', 'Prakash'],
    },
    {
      id: 'mehta-huf',
      name: 'Mehta HUF',
      ownerType: 'HUF',
      taxSlabRate: 30,
      aliases: ['Family HUF'],
    },
    {
      id: 'kiara-mehta',
      name: 'Kiara Mehta',
      ownerType: 'Child',
      taxSlabRate: 0,
      aliases: ['Kiara'],
    },
  ],
  institutions: [
    {
      id: 'hdfc-bank',
      name: 'HDFC Bank',
      branches: [
        { id: 'andheri-west', name: 'Andheri West' },
        { id: 'borivali', name: 'Borivali' },
      ],
    },
    {
      id: 'sbi',
      name: 'State Bank of India',
      branches: [
        { id: 'fort', name: 'Fort' },
        { id: 'thane', name: 'Thane' },
      ],
    },
    {
      id: 'icici-bank',
      name: 'ICICI Bank',
      branches: [
        { id: 'bandra-kurla-complex', name: 'Bandra Kurla Complex' },
        { id: 'powai', name: 'Powai' },
      ],
    },
    {
      id: 'post-office',
      name: 'India Post',
      branches: [
        { id: 'dadar-head-office', name: 'Dadar Head Office' },
      ],
    },
    {
      id: 'pfc',
      name: 'Power Finance Corporation',
      branches: [
        { id: 'demat', name: 'Demat' },
      ],
    },
  ],
  instrumentTypes: [
    { id: 'fixed-deposit', name: 'Fixed Deposit' },
    { id: 'scss', name: 'SCSS' },
    { id: 'tax-saver-fd', name: 'Tax Saver FD' },
    { id: 'corporate-bond', name: 'Corporate Bond' },
    { id: 'ncd', name: 'NCD' },
  ],
}

export const demoDeposits = [
  {
    id: 'demo-fd-aarav-hdfc-2024',
    srNo: 1,
    bankName: 'HDFC Bank',
    branchCity: 'Andheri West',
    holderName: 'Aarav Mehta',
    fundingSource: 'Aarav Mehta',
    instrumentType: 'Fixed Deposit',
    calculationFrequency: 'QUARTERLY',
    payoutMode: 'on-maturity',
    yearlyPayoutMonthDay: '',
    interestPayoutBeforeTds: '',
    interestPayoutAfterTds: '',
    accountNumber: 'DEMO-HDFC-1001',
    tenureYears: 2,
    tenureMonths: 0,
    tenureDays: 0,
    interestRate: 7.25,
    principalAmount: 500000,
    investmentDate: '2024-07-15',
    maturityDate: '2026-07-15',
    maturityBeforeTax: 577400,
    maturityAfterTax: 569660,
    totalInterestEarned: 69660,
    tdsPercent: 10,
    tdsAmount: 7740,
    status: 'Open',
    allocations: [],
    cashSettlements: [],
    notes: 'Cumulative FD used as a maturity rollover source in the demo.',
  },
  {
    id: 'demo-fd-nisha-sbi-quarterly-2024',
    srNo: 2,
    bankName: 'State Bank of India',
    branchCity: 'Thane',
    holderName: 'Nisha Mehta',
    fundingSource: 'Nisha Mehta',
    instrumentType: 'Fixed Deposit',
    calculationFrequency: 'SIMPLE',
    payoutMode: 'quarterly-fy',
    yearlyPayoutMonthDay: '',
    interestPayoutBeforeTds: 12600,
    interestPayoutAfterTds: 11340,
    accountNumber: 'DEMO-SBI-2202',
    tenureYears: 3,
    tenureMonths: 0,
    tenureDays: 0,
    interestRate: 7.1,
    principalAmount: 720000,
    investmentDate: '2024-04-01',
    maturityDate: '2027-04-01',
    maturityBeforeTax: 720000,
    maturityAfterTax: 720000,
    totalInterestEarned: 0,
    tdsPercent: 10,
    tdsAmount: 0,
    status: 'Open',
    allocations: [],
    cashSettlements: [
      {
        eventId: 'interest:demo-fd-nisha-sbi-quarterly-2024:2024-09-30',
        amount: 3400,
        settledAt: '2024-10-02',
      },
    ],
    notes: 'Quarterly payout FD with one settled interest receipt and later reinvestment links.',
  },
  {
    id: 'demo-scss-prakash-2023',
    srNo: 3,
    bankName: 'India Post',
    branchCity: 'Dadar Head Office',
    holderName: 'Prakash Mehta',
    fundingSource: 'Prakash Mehta',
    instrumentType: 'SCSS',
    calculationFrequency: 'SIMPLE',
    payoutMode: 'quarterly-fy',
    yearlyPayoutMonthDay: '',
    interestPayoutBeforeTds: 20500,
    interestPayoutAfterTds: 18450,
    accountNumber: 'DEMO-SCSS-3303',
    tenureYears: 5,
    tenureMonths: 0,
    tenureDays: 0,
    interestRate: 8.2,
    principalAmount: 1000000,
    investmentDate: '2023-05-10',
    maturityDate: '2028-05-10',
    maturityBeforeTax: 1000000,
    maturityAfterTax: 1000000,
    totalInterestEarned: 0,
    tdsPercent: 10,
    tdsAmount: 0,
    status: 'Open',
    allocations: [],
    cashSettlements: [],
    notes: 'Senior citizen quarterly income product.',
  },
  {
    id: 'demo-fd-huf-icici-closed-2022',
    srNo: 4,
    bankName: 'ICICI Bank',
    branchCity: 'Powai',
    holderName: 'Mehta HUF',
    fundingSource: 'Mehta HUF',
    instrumentType: 'Fixed Deposit',
    calculationFrequency: 'QUARTERLY',
    payoutMode: 'on-maturity',
    yearlyPayoutMonthDay: '',
    interestPayoutBeforeTds: '',
    interestPayoutAfterTds: '',
    accountNumber: 'DEMO-ICICI-4404',
    tenureYears: 3,
    tenureMonths: 0,
    tenureDays: 0,
    interestRate: 6.85,
    principalAmount: 400000,
    investmentDate: '2022-09-20',
    maturityDate: '2025-09-20',
    maturityBeforeTax: 490200,
    maturityAfterTax: 481180,
    totalInterestEarned: 81180,
    tdsPercent: 10,
    tdsAmount: 9020,
    status: 'Closed',
    allocations: [],
    cashSettlements: [],
    notes: 'Closed cumulative FD whose maturity proceeds partially fund newer records.',
  },
  {
    id: 'demo-fd-aarav-rollover-2025',
    srNo: 5,
    bankName: 'HDFC Bank',
    branchCity: 'Borivali',
    holderName: 'Aarav Mehta',
    fundingSource: 'Mehta HUF',
    instrumentType: 'Fixed Deposit',
    calculationFrequency: 'QUARTERLY',
    payoutMode: 'on-maturity',
    yearlyPayoutMonthDay: '',
    interestPayoutBeforeTds: '',
    interestPayoutAfterTds: '',
    accountNumber: 'DEMO-HDFC-5505',
    tenureYears: 1,
    tenureMonths: 6,
    tenureDays: 0,
    interestRate: 7.05,
    principalAmount: 300000,
    investmentDate: '2025-09-25',
    maturityDate: '2027-03-25',
    maturityBeforeTax: 333100,
    maturityAfterTax: 329790,
    totalInterestEarned: 29790,
    tdsPercent: 10,
    tdsAmount: 3310,
    status: 'Open',
    allocations: [
      {
        eventId: 'maturity:demo-fd-huf-icici-closed-2022',
        amount: 300000,
      },
    ],
    cashSettlements: [],
    notes: 'Rollover funded by the closed HUF FD maturity.',
  },
  {
    id: 'demo-fd-nisha-interest-reinvest-2025',
    srNo: 6,
    bankName: 'State Bank of India',
    branchCity: 'Fort',
    holderName: 'Nisha Mehta',
    fundingSource: 'Nisha Mehta',
    instrumentType: 'Fixed Deposit',
    calculationFrequency: 'SIMPLE',
    payoutMode: 'on-maturity',
    yearlyPayoutMonthDay: '',
    interestPayoutBeforeTds: '',
    interestPayoutAfterTds: '',
    accountNumber: 'DEMO-SBI-6606',
    tenureYears: 1,
    tenureMonths: 0,
    tenureDays: 0,
    interestRate: 6.9,
    principalAmount: 22680,
    investmentDate: '2025-04-05',
    maturityDate: '2026-04-05',
    maturityBeforeTax: 24245,
    maturityAfterTax: 24088,
    totalInterestEarned: 1408,
    tdsPercent: 10,
    tdsAmount: 157,
    status: 'Closed',
    allocations: [
      {
        eventId: 'interest:demo-fd-nisha-sbi-quarterly-2024:2024-12-31',
        amount: 11340,
      },
      {
        eventId: 'interest:demo-fd-nisha-sbi-quarterly-2024:2025-03-31',
        amount: 11340,
      },
    ],
    cashSettlements: [],
    notes: 'Small FD made entirely from received quarterly interest payouts.',
  },
  {
    id: 'demo-bond-aarav-pfc-2025',
    srNo: 7,
    bankName: 'Power Finance Corporation',
    branchCity: 'Demat',
    holderName: 'Aarav Mehta',
    fundingSource: 'Aarav Mehta',
    instrumentType: 'Corporate Bond',
    calculationFrequency: 'SIMPLE',
    payoutMode: 'yearly-fixed',
    yearlyPayoutMonthDay: '09-15',
    interestPayoutBeforeTds: 36000,
    interestPayoutAfterTds: 32400,
    accountNumber: 'DEMO-PFC-7707',
    tenureYears: 4,
    tenureMonths: 0,
    tenureDays: 0,
    interestRate: 7.2,
    principalAmount: 500000,
    investmentDate: '2025-09-15',
    maturityDate: '2029-09-15',
    maturityBeforeTax: 500000,
    maturityAfterTax: 500000,
    totalInterestEarned: 0,
    tdsPercent: 10,
    tdsAmount: 0,
    status: 'Open',
    allocations: [],
    cashSettlements: [],
    notes: 'Annual payout bond/NCD style instrument.',
  },
  {
    id: 'demo-tax-saver-kiara-2025',
    srNo: 8,
    bankName: 'ICICI Bank',
    branchCity: 'Bandra Kurla Complex',
    holderName: 'Kiara Mehta',
    fundingSource: 'Aarav Mehta',
    instrumentType: 'Tax Saver FD',
    calculationFrequency: 'QUARTERLY',
    payoutMode: 'on-maturity',
    yearlyPayoutMonthDay: '',
    interestPayoutBeforeTds: '',
    interestPayoutAfterTds: '',
    accountNumber: 'DEMO-ICICI-8808',
    tenureYears: 5,
    tenureMonths: 0,
    tenureDays: 0,
    interestRate: 7.0,
    principalAmount: 150000,
    investmentDate: '2025-04-10',
    maturityDate: '2030-04-10',
    maturityBeforeTax: 212500,
    maturityAfterTax: 206250,
    totalInterestEarned: 56250,
    tdsPercent: 10,
    tdsAmount: 6250,
    status: 'Open',
    allocations: [],
    cashSettlements: [],
    notes: 'Child-linked example with zero slab in master data.',
  },
  {
    id: 'demo-fd-prakash-monthly-2026',
    srNo: 9,
    bankName: 'HDFC Bank',
    branchCity: 'Andheri West',
    holderName: 'Prakash Mehta',
    fundingSource: 'Prakash Mehta',
    instrumentType: 'Fixed Deposit',
    calculationFrequency: 'SIMPLE',
    payoutMode: 'quarterly-fy',
    yearlyPayoutMonthDay: '',
    interestPayoutBeforeTds: 6750,
    interestPayoutAfterTds: 6075,
    accountNumber: 'DEMO-HDFC-9909',
    tenureYears: 2,
    tenureMonths: 0,
    tenureDays: 0,
    interestRate: 7.5,
    principalAmount: 360000,
    investmentDate: '2026-01-15',
    maturityDate: '2028-01-15',
    maturityBeforeTax: 360000,
    maturityAfterTax: 360000,
    totalInterestEarned: 0,
    tdsPercent: 10,
    tdsAmount: 0,
    status: 'Open',
    allocations: [],
    cashSettlements: [],
    notes: 'Newer quarterly payout product for upcoming interest timeline.',
  },
  {
    id: 'demo-ncd-huf-2024',
    srNo: 10,
    bankName: 'Power Finance Corporation',
    branchCity: 'Demat',
    holderName: 'Mehta HUF',
    fundingSource: 'Mehta HUF',
    instrumentType: 'NCD',
    calculationFrequency: 'SIMPLE',
    payoutMode: 'yearly-fixed',
    yearlyPayoutMonthDay: '12-01',
    interestPayoutBeforeTds: 31500,
    interestPayoutAfterTds: 28350,
    accountNumber: 'DEMO-PFC-1010',
    tenureYears: 3,
    tenureMonths: 0,
    tenureDays: 0,
    interestRate: 7.0,
    principalAmount: 450000,
    investmentDate: '2024-12-01',
    maturityDate: '2027-12-01',
    maturityBeforeTax: 450000,
    maturityAfterTax: 450000,
    totalInterestEarned: 0,
    tdsPercent: 10,
    tdsAmount: 0,
    status: 'Open',
    allocations: [],
    cashSettlements: [],
    notes: 'HUF annual income example.',
  },
  {
    id: 'demo-fd-aarav-archive-example',
    srNo: 11,
    bankName: 'State Bank of India',
    branchCity: 'Fort',
    holderName: 'Aarav Mehta',
    fundingSource: 'Aarav Mehta',
    instrumentType: 'Fixed Deposit',
    calculationFrequency: 'QUARTERLY',
    payoutMode: 'on-maturity',
    yearlyPayoutMonthDay: '',
    interestPayoutBeforeTds: '',
    interestPayoutAfterTds: '',
    accountNumber: 'DEMO-SBI-1111',
    tenureYears: 1,
    tenureMonths: 0,
    tenureDays: 0,
    interestRate: 6.5,
    principalAmount: 100000,
    investmentDate: '2024-01-10',
    maturityDate: '2025-01-10',
    maturityBeforeTax: 106650,
    maturityAfterTax: 105985,
    totalInterestEarned: 5985,
    tdsPercent: 10,
    tdsAmount: 665,
    status: 'Closed',
    allocations: [],
    cashSettlements: [],
    notes: 'Closed record kept for filter and lifecycle demonstrations.',
  },
  {
    id: 'demo-fd-huf-partial-rollover-2025',
    srNo: 12,
    bankName: 'ICICI Bank',
    branchCity: 'Powai',
    holderName: 'Mehta HUF',
    fundingSource: 'Mehta HUF',
    instrumentType: 'Fixed Deposit',
    calculationFrequency: 'QUARTERLY',
    payoutMode: 'on-maturity',
    yearlyPayoutMonthDay: '',
    interestPayoutBeforeTds: '',
    interestPayoutAfterTds: '',
    accountNumber: 'DEMO-ICICI-1212',
    tenureYears: 2,
    tenureMonths: 0,
    tenureDays: 0,
    interestRate: 7.15,
    principalAmount: 120000,
    investmentDate: '2025-10-05',
    maturityDate: '2027-10-05',
    maturityBeforeTax: 138400,
    maturityAfterTax: 136560,
    totalInterestEarned: 16560,
    tdsPercent: 10,
    tdsAmount: 1840,
    status: 'Open',
    allocations: [
      {
        eventId: 'maturity:demo-fd-huf-icici-closed-2022',
        amount: 120000,
      },
    ],
    cashSettlements: [],
    notes: 'Second partial reinvestment from the same maturity pool.',
  },
]

export const buildDemoPortfolioSnapshot = (ownerUserId = DEFAULT_DEMO_OWNER_ID) => ({
  ownerUserId,
  portfolioLabel: DEMO_PORTFOLIO_LABEL,
  masterData: demoMasterData,
  deposits: demoDeposits.map((deposit) => ({
    ...deposit,
    ownerUserId,
    createdByUserId: ownerUserId,
    updatedByUserId: ownerUserId,
    isDeleted: false,
  })),
})
